Add new staging and prod Superset environments
ctoec/data-visualization pull request #26
Opened 2021-02-25 23:03 UTC by JordanGuinn

## Background
Provide a brief overview of the work completed here.

## GitHub Issue
https://github.com/skylight-hq/ctoec-devops/issues/196

## Associated PRs
https://github.com/skylight-hq/ctoec-devops/pull/202

## Validation Plan
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.

2021-04-13 21:02 UTC, JordanGuinn commented on docker-compose.yml
> +version: "3.7"
Need this to be at the root of the project

2021-04-14 13:41 UTC, kmagida110 requested changes
A few small questions but overall this seems like a good set up

2021-04-14 13:41 UTC, kmagida110 commented on docker-compose.yml
> +version: "3.7"
OK, that should be fine, can you update the volumes to be in the docker folder as well?

2021-04-14 13:41 UTC, kmagida110 commented on docker/.env
> +
nit: extra space

2021-04-14 13:41 UTC, kmagida110 commented on .circleci/config.yml
> +            SUPERSET_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/admin/password --query 'SecretString' --output text) && echo -e "ADMIN_PA
Is there a reason that we will need the admin password that you know of? I'm fine with just keeping the Superset User accessible to the app

2021-04-14 13:41 UTC, kmagida110 commented on .circleci/config.yml
> +            eb ssh ece-pensieve-<< parameters.env >>-env --command "docker exec -it superset superset fab create-admin --username 'voldemort' --firstname 'ADMIN' --lastname 'USER' --email 'admin@ctoe
Is the plan here that we would change this user and password in production? I'm a little hesitant about having this in plain text

2021-04-14 16:29 UTC, JordanGuinn commented on .circleci/config.yml
> +            eb ssh ece-pensieve-<< parameters.env >>-env --command "docker exec -it superset superset fab create-admin --username 'voldemort' --firstname 'ADMIN' --lastname 'USER' --email 'admin@ctoe
oh this will **for sure** not be the end result - this is one of the things I'm still ironing out

2021-04-14 16:33 UTC, JordanGuinn commented on .circleci/config.yml
> +            SUPERSET_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/admin/password --query 'SecretString' --output text) && echo -e "ADMIN_PA
I'd think just initially, in order to create new users the first time we kick off the app.  Also my personal take is that it's generally just better to have creds and not need them than to need them and not have them, but I can potentially be swayed away from that.

2021-04-14 17:47 UTC, kmagida110 commented on .circleci/config.yml
> +            SUPERSET_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/admin/password --query 'SecretString' --output text) && echo -e "ADMIN_PA
I'm definitely for having it, I just don't think we use it anywhere and limiting the places where it exists in production seems like a good thing. Again, I'm not too tied to either way myself.

2021-04-14 17:47 UTC, kmagida110 approved these changes

2021-04-20 05:31 UTC, JordanGuinn commented on docker-compose.yml
> +version: "3.7"
Update - seems like the volume paths are already prepended with the docker directory (potentially from the specifying of the env file?), because adding `docker` to the volume paths breaks deploys.

2021-04-20 13:41 UTC, kmagida110 commented on docker-compose.yml
> +version: "3.7"
Where (both in the pipeline and the folder is the actual docker-compose being run? How is it breaking the deploys ie. what is the error message?

2021-04-20 15:18 UTC, JordanGuinn commented on docker-compose.yml
> +version: "3.7"
CI pipeline doesn't care - I slightly misspoke.  Deploy is succeeding without issue, but the `docker-compose` command is just failing to start once the deploy completes.  The Beanstalk error is pretty convoluted, but effectively there was no `docker-compose` PID indicating a running process, which went away when I moved the paths back.

2021-04-20 15:26 UTC, kmagida110 commented on docker-compose.yml
> +version: "3.7"
Hmm, very strange, I wonder where the error was coming in. Regardless LMK when it is set up from your end and I'll do some smoke testing to see if everything is working as expected.

2021-04-22 02:01 UTC, JordanGuinn commented on .circleci/config.yml
> +            SUPERSET_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/admin/password --query 'SecretString' --output text) && echo -e "ADMIN_PA
It only exists in secrets manager, and it'll need to be used initially to create additional users, no?  Unless that's previously just been done from the CLI?

2021-04-22 02:21 UTC, JordanGuinn commented on docker-compose.yml
> +version: "3.7"
Should be good to test now!

2021-04-22 12:39 UTC, bamader approved these changes

2021-04-22 12:39 UTC, bamader commented on .circleci/config.yml
> -      - checkout
Maybe it's because I'm still weak at terraform, but did these steps actually get moved over to terraform/pensieve? I didn't see anything about installing git.

2021-04-22 12:39 UTC, bamader commented on .platform/hooks/postdeploy/01_https_server.sh
> +# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html
For educational purposes, could I get a brief rundown of what's happening here? Jordan, I'm guessing this is related to the things we talked about on Tuesday with the AWS docs just straight lying about parameters, but what's the actual issue this is fixing?

2021-04-22 13:23 UTC, kmagida110 commented on docker-compose.yml
> +version: "3.7"
Where is the link?

2021-04-22 13:25 UTC, kmagida110 commented on .circleci/config.yml
> +            SUPERSET_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/admin/password --query 'SecretString' --output text) && echo -e "ADMIN_PA
I 100% misunderstood this, I thought it was the DB admin, the Superset Admin makes sense. I had been using the CLI and then changing the password in the UI. This is completely fine for an initialization that will likely never happen again. Actually, we may never need it ever because we'll port the existing DB into this one with all its current users.

2021-04-22 13:28 UTC, kmagida110 commented on .circleci/config.yml
> -# # One time init of database
Was this moved elsewhere? The db init and user creation process might be useful to have documented even if they aren't in the pipeline.

2021-04-22 13:29 UTC, kmagida110 commented on .circleci/config.yml
> -# # One time init of database
Never mind, found it!

2021-04-22 14:15 UTC, kmagida110 approved these changes
Looks good! Where is the link so I can take a look?

2021-04-26 20:03 UTC, kmagida110 commented
@JordanGuinn The superset config isn't being pulled into the initialization of Superset. The metadata for the dashboards isn't showing up in the database where it is supposed to and, much more trivially, the new logo isn't showing up either. I assume this is happing because the app isn't finding the config file when it starts up and is instead using the base config. We just need to find a way to get the config into the Pythonpath while it is starting up.

2021-04-26 20:07 UTC, JordanGuinn commented on .circleci/config.yml
> -      - checkout
Yes!  This entire workflow was responsible for setting up the docker environment that Superset is running in on our current prod instance.  We get all that for free with Elastic Beanstalk, as they provide out-of-the-box Docker environments that we can just _use_

2021-04-26 20:09 UTC, JordanGuinn commented on .platform/hooks/postdeploy/01_https_server.sh
> +# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html
This is configuring NGINX (our proxy server) to take all traffic received on port 443 (HTTPS) and route it to port 8088, which is the port Superset is running on.  Ideally this would just be an `https.conf` NGINX config file that we give Elastic Beanstalk, but for whatever reason ELB was simply not using that file in it's NGINX setup.  So the surrounding bash commands within this script forcibly do that very thing on each deploy.

2021-04-26 20:10 UTC, JordanGuinn commented on docker-compose.yml
> +version: "3.7"
For posterity's sake: http://staging.ece-pensieve.ctoecskylight.com/

2021-04-27 15:57 UTC, kmagida110 commented on .circleci/config.yml
> +            MAPBOX_API_KEY=$(aws secretsmanager get-secret-value --secret-id /data-viz/map_box/key --query 'SecretString' --output text) && echo -e "MAPBOX_API_KEY=$MAPBOX_API_KEY" >> docker/.env
I bet this was what caused the initial failure when you changed the volumes

2021-04-27 15:57 UTC, kmagida110 commented on docker/config/superset_config.py
> +ENABLE_PROXY_FIX = True
What did this do?

2021-04-27 15:59 UTC, JordanGuinn commented on .circleci/config.yml
> +            MAPBOX_API_KEY=$(aws secretsmanager get-secret-value --secret-id /data-viz/map_box/key --query 'SecretString' --output text) && echo -e "MAPBOX_API_KEY=$MAPBOX_API_KEY" >> docker/.env
Yep!  Almost assuredly 😭

2021-04-27 16:02 UTC, JordanGuinn commented on docker/config/superset_config.py
> +ENABLE_PROXY_FIX = True
[According to the docs](https://superset.apache.org/docs/installation/configuring-superset), that param is supposed to extract and use the forwarding headers from a given incoming request, now necessary that this is behind a load balancer.

2021-04-27 23:30 UTC, merged