BALLER script
ctoec/data-visualization pull request #28
Opened 2021-03-01 23:53 UTC by bamader

## Background
This PR uploads the script I used to make the expanded demographics of Connecticut data set. It leverages a few modular functions that work with the censusdata package to easily and quickly block download requested fields for all towns in CT. Fields are specified using two "dictionary" files to help the package parse the correct variables, since census data tables have a gross kind of layering that nests variables (coded by "uniqueId") inside of tables (coded by "tableId"--one table can be associated with as many as 30 variables). This script handles raw table aggregation to create any desired field specified.

2021-03-02 17:05 UTC, kmagida110 requested changes
A bunch of feedback here but overall I like the concept. I'd say that this is a good setup for pulling data in bulk and keeping track of fields. I have some minor tweaks (using pandas more for data wrangling) and don't think we should drop any fields so we can change our analysis in the future.

2021-03-02 17:05 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +df = pd.concat([df_single, df_combination], axis=1)
Should we be concatenating here? Are both of the dataframes ordered by town? If so, can we add a check to make sure the town rows line up with each other?

2021-03-02 18:27 UTC, bamader commented on data_sets/expanded_town_demographics/combination_field_lookups.txt
> +# FORMAT
What exactly is the purpose of the data_integration directory? This doesn't feel like a data_integration thing. I actually thought it was specifically for generating a new dataset to use with _other_ work?

2021-03-02 18:28 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +COMBINATIONN_FIELD_FILE = "combination_field_lookups.txt"
Good catch, my 'n' key has been sticking lately 🙄

2021-03-02 18:31 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +STATE_CODE = '09'
It doesn't feel like defining a constant is enough of a reason to use a package imo. Also, I would actually argue _against_ renaming state code to be FIPS. State code is an immediately comprehensible variable name while I have no idea what FIPS is (you also mentioned in another comment suggesting changes based on people not familiar with pulling census data, so this feels like it's in that vein too). Not a hill I feel *super* strongly about keeping, but I do think this is more readable.

2021-03-02 18:33 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +'''
Didn't know that. I've always hated the aesthetic of documentation inside the function (I think it makes the code much uglier and in some ways harder to read), but I could go either way here

2021-03-02 18:37 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +    with open(filename, 'r') as fp:
Not really sure what you mean? Why would we use pandas for just text file parsing? This function builds up the arrays that are used for other things to actually download and process data, but I don't think pandas provides any cleaner or more 'legible' way to split and group strings.

2021-03-02 19:11 UTC, kmagida110 commented on data_sets/expanded_town_demographics/combination_field_lookups.txt
> +# FORMAT
I was thinking this is one of the datasets that we are integrating, or at least it will be. Theoretically this analysis will be something that we want to have more sustainably for them.

2021-03-02 19:13 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +STATE_CODE = '09'
Yeah, I agree on the package, just an FYI. I would just a link or something to where you got the State Code and what state it corresponds to.

2021-03-02 19:15 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +'''
Yeah, if you put it in the function it is recognized as a docstring associated with the function: https://www.python.org/dev/peps/pep-0257/. Outside the function leaves some ambiguity surrounding what it is associated with (a block of code/multiple functions/etc.)

2021-03-02 19:20 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +df[df < 0] = nan
Nope no fields should be less than 0. Every field we're pulling is a population count or a dollar amount, and I think we've got a big problem if any of those come back negatives 😛 . The one thing I did find was that when the census didn't have info on a field, rather than giving it a NaN or a blank or something, they populated it with "-666666666" (give or take a few 6's). So this code replaces those garbage negative values with NaNs. I did this instead of putting in 0s or some other values because I thought that should be left to the analysis to decide what to do with these blanks.

2021-03-02 19:25 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +df['town'] = [str(x) for x in df.index]
This drops a bunch of useless text that comes prepended with every census geo object. A town's entry, for example, might read as "STATE Connecticut 050 > COUNTY 060 [county code] > SUBCOU [subcounty code] town TOWN 160". We just care about the town name so that's the only thing we keep here.

2021-03-02 19:30 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +df = df.loc[df['town'].apply(lambda x: True if 'town' in x else False), :]
What sort of information are you looking for? I felt like the comment about dropping census coding text was informative enough, but what do you think is missing?

2021-03-02 19:38 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +    with open(filename, 'r') as fp:
It is mostly to avoid using positional indicies and loops over the whole file which can stretch out the code. Pandas string functionality is actually pretty good. If you went that way you'd have to do some thinking around the multiple clusters in the same columns but most of the others are pretty straight-forward
```
df['solo_fields'] = df['solo_fields'].str.split(',') # returns a list 
```

2021-03-02 19:43 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +    for t in range(len(tables)):
Those tables are the outputs of the parse_combination_fields_file function above. It creates everything that this function uses to work.

2021-03-02 19:54 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +df = pd.concat([df_single, df_combination], axis=1)
Yes, concatenation is safe. The censusgeo object is what defines the order of both dataframes, and they get fetched in a deterministic order each time because of sub county code. I've checked that the results are the same as if we used join or merge, and they are.

2021-03-02 19:56 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +df[df < 0] = nan
OK, that is fine, I did some Googling and it looks like that is standard practice and there aren't many/any actually negative fields in the API so it should be fine.

2021-03-02 19:57 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +df['town'] = [str(x) for x in df.index]
Cool, it is weird that all of that is not included in the string representation

2021-03-02 19:58 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +df = df.loc[df['town'].apply(lambda x: True if 'town' in x else False), :]
I assume what this is doing is dropping the ~4 county subgeographies that aren't formally towns, is that not what it is doing?

2021-03-02 20:00 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +    for t in range(len(tables)):
OK, I was thrown by the tables, I have been thinking of those as more variables or estimates. ie. B20002_004E is a variable and B20002 is a table, is that off?

2021-03-02 20:02 UTC, kmagida110 commented on data_sets/expanded_town_demographics/field_lookup.py
> +df = pd.concat([df_single, df_combination], axis=1)
Can we add in a len check just in case if there is some field or field combination that doesn't have the same number of geos as another set?

2021-03-02 20:05 UTC, bamader commented on data_sets/expanded_town_demographics/field_lookup.py
> +df = pd.concat([df_single, df_combination], axis=1)
That can't happen. It's the same geo object used for both calls (single variables and block variables) so there's only ever one set of towns. If a table doesn't have specific variable info for that town, that's where you get the -666666 from.

2021-03-02 20:18 UTC, bamader commented
Two general comments:
1) The code already supports not removing columns if that's how you choose to parse things. Based on how I defined the combination file's parsing system, you can choose to have the script do the aggregating for you or you could do it yourself. If you're like me and you don't actually care about the raw individual columns, just put the numbers and names in the combination_field portion of the text line. If you want to save the individual columns and still do block table retrieval, you can do that with no code changes just by putting the numbers and names in the solo field portion. Here's an example:

```
the format is:
    root name; table code; highest field number; solo fields; solo names; fields to aggregate; aggregated names
so the format to aggregate like I prefer is:
    myTable; B12345; 6; ; ; 1,2,3,4,5,6; sum_of_columns
the format to keep everything like you prefer is:
    myTable; B12345; 6; 1,2,3,4,5,6; col1, col2, col3, col4, col5, col6; ;
```
Basically the script already gives you the option and control to drop or not, and I think depending on your perspective and desired use case that functionality is really good (e.g. maybe for your process of estimating demand it's helpful to know number of kindergartners vs nursery school students vs preschool vs 1st grade vs ..., but for me just collecting overall demographic info that's a lot of variable clutter when an aggregate like K-12 captures what I actually care about). I firmly believe we should not take out the option to have it do aggregations for us.

2) Real talk, I think we're getting a little too deep into the weeds with "correcting" the script. Everything in here works as is, and while there are definitely some styling/formatting/efficiency things that are easy and good improvements to make, I think some of the checks and changes asked aren't that helpful for us since we're going to own this script (e.g. it really doesn't feel worth the time and effort to change the text parsing functionality to pandas when that would complicate the aggregation functionality that's important to overall demographic collection). I'm always game for critical code evaluation, but it's just my two cents that we should keep the actual *use* of the script in perspective, because the generated data is what's the valuable thing, not the script itself.

Def open to other perspectives, though, @jlhogan or @JordanGuinn if you have them! Also happy to keep refining the script if y'all think it needs it. Just wanted to say my piece before we went too deep.

2021-03-02 21:10 UTC, kmagida110 commented
@bamader On point 1, that is fine, I'm 

On the 2nd, I don't want to get too far into the weeds and you are right that the data is the most important part. It can be fine as is, I'm really just trying to get us to a place where have a shared understanding and approach to problems and am using PRs for that. If you'd rather do that some other way that's OK. I'm also looking at this as code that will be used as production like code that others will use and edit without context because I've been burned too many times.

2021-03-02 21:20 UTC, kmagida110 approved these changes

2021-03-02 21:30 UTC, bamader commented
Thanks for clarifying your context, Kyle. Apologies if I came off as standoffish (was not at all the intent). I just wanted to express that perspective for the good of thought sharing. I know we're still refining our process and how we generate/share knowledge. If we need to "productionize" anything in our repo before some handoff that approaches, we can definitely do that.

2021-03-03 21:05 UTC, imcurtis commented on data_sets/expanded_town_demographics/field_lookup.py
> +                else:
When would you expect this part to throw an error? Would Census data have to be formatted a certain way, or be missing something?

2021-03-03 21:18 UTC, imcurtis commented on data_sets/expanded_town_demographics/single_field_lookups.txt
> +# FORMAT
Yep, saying pretty much the same!

2021-03-03 21:19 UTC, imcurtis approved these changes

2021-03-04 13:15 UTC, merged