changed files
ctoec/data-visualization pull request #32
Opened 2021-03-09 16:00 UTC by imcurtis

## Background

Taking @bamader's script and adding some new fields for analysis. What results is a Jupyter notebook with some analyses and added calculations for demand estimation. The fourth model for demand estimation is taken from the following paper: https://www.urban.org/sites/default/files/publication/97286/mapping_child_care_demand_and_the_supply_of_care_for_subsidized_families.pdf. The two components are tabulating children under 200% of the poverty level and the percentage of households where all parents are working.

## GitHub Issue
Replace this text with the GitHub issue link.
**NOTE: Please don't mark the issue as closed by this pull request!  Issues are to be closed manually within Zenhub upon merge & prod deploy.**

## Associated PRs
If applicable, replace this text with links to additional pull requests associated with this work.

## Validation Plan
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.

## Additional Context
If there's anything additional information that those reviewing or validating this work should be aware of, please specify it here.

2021-03-09 16:50 UTC, bamader commented
Couple of notes:
1. Your .ipynb file is showing having 11,000 changes, which strikes me as kind of suspicious (like I can't imagine you wrote 11k new lines of code, so what's happening there? Are you committing more code here than you intended/changing things you didn't mean to?). I could totally be wrong on this point, but it's something to look at to make sure that those change lines are valid.
2. I would strongly prefer that we make new text files for new data sets. In this case, I made the two text files `single_field_lookups` and `combination_field_lookups` to address general town demographics. In this case, I think we're actually building a new data set, specifically "corrected_demand_estimates." I'd rather see two new text files for demand_single_lookups and demand_combo_lookups and have these be in a new folder called 'demand_estimation' or something like that. I think there's definitely an argument to be made for _eventually_ combining data sets into a single unified csv that has town name, geo information, demographic features, true demand, etc., but I think because right now we're all making a bunch of different raw data sets, trying to concatenate columns onto the same csv will only get cumbersome as we try to refine. I think once we have true demand estimates, and once I run them through the feature predictor to see what matters, we should start conjoining datasets then because they'll be taking on a more final form. Just my two cents!

2021-03-09 17:06 UTC, imcurtis commented
@bamader:

In response to your first question, I think this has to do with changing the csv file, but I am not completely sure on that. 

For your second question/point that is very doable and I can make the changes you suggested, I just prefer to do it after we hear back about how they want these results to be presented to OEC.

2021-03-09 19:54 UTC, kmagida110 requested changes
A few structural suggestions but you have a lot of good models here and they are a good base

2021-03-09 19:54 UTC, kmagida110 commented on src/data_integration/unmet_needs/census_data/.idea/.gitignore
> +# Default ignored files
Can you add the whole ./idea folder to the main gitignore?

2021-03-09 19:54 UTC, kmagida110 commented on data_sets/expanded_town_demographics/demand_estimations.ipynb
> +{
The reason this is so many lines is that you are printing the tables out.

I'll do all the comments here:

For model #1 the .5 is relatively arbitrary as is, you explained it to me so just add that explanation in the comments.

On the income to poverty ratio it might be visually easier to split up the lines for the numerator and the denominator. I would say we go for a ratio for under 200 to all population.

In general, now that you have done the exploration it might be better to make a script file with each estimation as a different function or set of functions.

2021-03-10 13:29 UTC, bamader commented on data_sets/expanded_town_demographics/demand_estimations.ipynb
> +{
Commenting here before actually checking out the notebook, but +1 for adding comment explanations (love me some code clarity) and +1 for separating out different models into different functions (or at least, functions which take an input parameter that tells it which model to run). I haven't been doing that as much with my code because it's been more data retrieval-y, but this script is actually doing meaningful calculation and aggregation so I think we should invest the time to modularize it well. I'll force myself to do the same thing on whatever predictive feature estimator I end up writing.

2021-03-11 17:37 UTC, closed without merging