Care demand estimation
ctoec/data-visualization pull request #34
Opened 2021-03-11 19:30 UTC by imcurtis

## Background
Based off of the suggestions that were made in a previous PR, I moved the files to the data_sets directory to consolidate the work we were doing with town level data.

## GitHub Issue
Replace this text with the GitHub issue link.
**NOTE: Please don't mark the issue as closed by this pull request!  Issues are to be closed manually within Zenhub upon merge & prod deploy.**

## Associated PRs
https://github.com/ctoec/data-visualization/pull/33

## Validation Plan
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.

## Additional Context
If there's anything additional information that those reviewing or validating this work should be aware of, please specify it here.

2021-03-11 20:35 UTC, bamader reviewed
I've got some questions spread throughout just about the organization of some of the files. It strikes me that there are a ton of files being changed / added and I'm not sure why (looks like some of them have been duplicated, i.e. there's both a `town_demandEstimated_data.csv` and a `town_demand_data.csv` with 170 rows and that seems to be different from the `town_demand_data.csv` in another subfolder). Do we actually need all these files to be uploaded to the repo? I would've thought there would be something like 6 or so files: 
- a demand_single_lookups file
- a demand_combo_lookups file
- the CSV you get from running my data collection script (census_data_for_demand_estimation.csv or something like that)
- the python notebook you used
- the python script you wrote
- the output CSV that results from running your script on the downloaded census data
I'm not sure where all these other files and changes are coming from, and that makes me very nervous to merge because I don't want to be messing with other structures or files.

2021-03-11 20:35 UTC, bamader commented on data_sets/demand_estimation/town_demand_estimated_data.csv
> +Deep River,0.0
What does this last number represent? I'm noticing some small values, including some 0's in here. Just want to make sure this is correct.

2021-03-11 20:35 UTC, bamader commented on data_sets/expanded_town_demographics/combination_field_lookups.txt
> +children under 6 by parent employment status; B23008; 13; 2,4,10,13; all categories, both parents - in labor force, only father - in labor force, only mother - in labor force; ;
Since you've got these moved to their own files now, let's take away the changes to this file and the single_field_lookups for expanded demographics

2021-03-11 20:35 UTC, bamader commented on data_sets/expanded_town_demographics/single_field_lookups.txt
> +median_family_income_in_the_past_12_months_in_2019_inflation-adjusted_dollars_by_family_size_total: B19119_001E
See comment on combination_field_lookups

2021-03-11 20:35 UTC, bamader commented on src/data_integration/demand_estimation/demand_combo_lookups.txt
> +
In the combo file for expanded demographics, you also had a field for median income by family size; did you also want to put that here?

2021-03-11 20:35 UTC, bamader commented on src/data_integration/demand_estimation/field_demand_lookup.py
> +TOWN_FILE = "town_data.csv"
What's going on with this file? Are you moving it or copying it or what? It looks like you copied my script over, but just want to make sure that was intended.

2021-03-11 20:44 UTC, imcurtis commented on data_sets/demand_estimation/town_demand_estimated_data.csv
> +Deep River,0.0
This would most likely mean that there are 0% of the households where all parents in it are working

2021-03-11 20:46 UTC, imcurtis commented on data_sets/expanded_town_demographics/combination_field_lookups.txt
> +children under 6 by parent employment status; B23008; 13; 2,4,10,13; all categories, both parents - in labor force, only father - in labor force, only mother - in labor force; ;
Are you referring to the other files?

2021-03-11 20:47 UTC, imcurtis commented on src/data_integration/demand_estimation/demand_combo_lookups.txt
> +
I ended up not using that

2021-03-11 20:47 UTC, imcurtis commented on src/data_integration/demand_estimation/field_demand_lookup.py
> +TOWN_FILE = "town_data.csv"
Definitely not intended, still trying to figure out how to do PRs in a way that are clean. Not sure why this is happening

2021-03-11 21:01 UTC, bamader commented on src/data_integration/demand_estimation/field_demand_lookup.py
> +TOWN_FILE = "town_data.csv"
Yeah it's all good. With this PR, because this is representing a blocking artifact, I would just focus on getting the six or seven files you actually used up on github, and then I can handle reorganization and reformatting when I push my feature analysis code. That way we're not stuck on something that's not adding value.

2021-03-11 21:51 UTC, kmagida110 requested changes
Good once the files are squared away, LMK if you want a hand with those

2021-03-11 21:51 UTC, kmagida110 commented on data_sets/demand_estimation/town_demand_estimated_data.csv
> +Deep River,0.0
Or is it that the demand estimate is 0, that is definitely possible

2021-03-11 21:51 UTC, kmagida110 commented on data_sets/demand_estimation/demand_estimate_script.py
> +def demand_estimate_income_housing(housing_lower, female, male):
Not blocking but next time you can do a general ratio function and pass it whichever multiplier you want to pass

2021-03-11 22:10 UTC, kmagida110 approved these changes
Let's do this!

2021-03-12 00:08 UTC, bamader approved these changes

2021-03-12 00:08 UTC, merged