Combine enrollment reports into single DF
ctoec/data-visualization pull request #41
Opened 2021-03-24 20:08 UTC by bamader

## Background
This PR provides a script that combines all the historical Care 4 Kids files from the past four years into a single pandas dataframe. The files are a non-standardized mess, so we'll just have to live with this script that unifies them as easily as possible.

## Additional Context
I don't think there's any extra context. We should just try to get this merged quickly so that we can unblock and work on analyzing / visualizing.

2021-03-24 20:58 UTC, imcurtis approved these changes

2021-03-24 21:15 UTC, kmagida110 requested changes
We can discuss live or async tomorrow but if there is a way to have this output a longer sheet with year, month, town (and maybe space type) on each row that will make analysis a lot easier.

2021-03-24 21:15 UTC, kmagida110 commented on data_sets/historical_care_4_kids/data_aggregation.py
> +# If it's the first file we process, just use that as the base DF
I don't think you need the df here, the one on line 217 will be the first one already

2021-03-24 21:15 UTC, kmagida110 commented on data_sets/historical_care_4_kids/data_aggregation.py
> +        while not have_headers:
Love inconsistent formatting

2021-03-24 21:15 UTC, kmagida110 commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
Is there any way this could be set up so that each row has a unique combination of at least year and month? It will be much easier to graph and do time series analysis or graphing if there is a consistent time column(s), the other type categories could be combined into a type column or each as their own column like it is now but having time as a row value will be really helpful.

2021-03-24 21:15 UTC, kmagida110 commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +Andover,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,2,1,0,2,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,3,2,5,1,0,2,0,0,0,3,0,0,0,0,0,0,0,3,0,0,0,0,2,5,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0
We can do this in the analysis too but it might be worth converting * and *** into what they should be or mean based on the information in the sheets.

2021-03-25 12:07 UTC, bamader commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
Yes I can definitely  work on re-structuring. Superset isn't yet intuitive to me, so  I format files the way I would use them for pure python based ML (in this case, in my mind, this df could simply be filtered with one line lambda functions on  the columns to get  everything from, say, 2017, or everything with infant/toddler, etc.). But I totally get that's not the best way to make them work for superset.

So, to be perfectly clear on the ask here, what you're looking for is a dataframe with 48 rows: one row for each unique combination of Month/Year (4 years of data, 12 months per  year)?  This would leave everything else as a column. I don't necessarily mind that the df  gets super wide,  but how will having all those columns help us do  graphing and filtering? For example, we know we'll want to have a town filter somewhere to see a particular town's infant/toddler, preschool, and school age enrollments over the course of time. With 48 rows, we'd have columns for each  combination of town, regulation type, and age category (e.g. Andover IT Regulated, Andover  IT  Unregulated, Ansonia Preschool Regulated, etc.).  Is this what you want?

Maybe the better phrasing of my clarifying question  is this: what would be the best way to divide into rows and columns the following fields: time (month +  year), town, age category, space type (regulated vs un)? In particular, what's the best way to partition the data so that  we'd be able to create the  following graphs:
1. a macro-level graph showing, for each year, changes in total enrollment of regulated and unregulated spaces
2. a medium-level graph showing, for each  town over each year, the total number of enrollments in that town
3. a micro-level graph showing, for a single given town over the  full 48 months, changes in enrollments for specific spaces?

I don't know if we'll necessarily make these three graphs,  but these are the kinds of things  I think we'll do so if we can solve  this problem with our sheet, we can solve any related problem. Sorry for the wordiness--again, superset is not yet my strength so having clarity on the structure will make it easier for me.

2021-03-25 13:42 UTC, kmagida110 commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
I think the best way to get all three of those options, and others that we haven't thought of yet is by having every row have the following columns (time, town, age, space type). That way the different charts can be sums of all rows grouped by 1. a year and regulated status, 2. Town and Year, 3. Town, year (filtered) and enrollment status. This is relevant for Superset but also for SQL. It is much easier to make the right query in SQL if you can say where space type = Regulated rather than dealing with columns. Superset is based on SQL so that makes it work there but it will also work for Tableau and direct SQL queries as well. Most other charts will flow from this type of grouping and filtering.

One thing we will have to think about is how we count yearly spaces. Is it the sum of monthly, the average of monthly, the max of monthly or something else? I'm sure they don't have an answer so we'll have to do the exploration.

2021-03-25 15:02 UTC, bamader commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
Okay I think I just had a breakthrough and overcame my conceptual hurdle. I've been building these CSV files to act as if each row is a feature vector for use in future ML. What you're saying here is that we actually want the CSVs to act as _databases_--fully schema'ed, filterable, searchable, databases, where each row is a _single_ record with a bunch of filterable params. In the C4K case, that might look like the following:

```
YEAR        MONTH        TOWN        AGE GROUP        SERVICE REGULATION        SPACE SETTING        ENROLLMENTS
2016        Apr                 Ansonia        IT                                Regulated                                Center                                4
2016        Jun                Ansonia            IT                            Unregulated                        Relative Care                        7
2016        Apr                 Ansonia        Preschool                    Regulated                                Group Home                17
```

2021-03-25 15:02 UTC, bamader commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
^^ Pretend that isn't formatted so hideously 😂

2021-03-25 15:04 UTC, bamader commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
Also:
1. do we want to combine YEAR and MONTH together into a single time column? I split them up in the above example for ease of filtering.
2. I think we should de-couple regulation with space setting. There are three or four options for regulations (Regulated, Exempt, Unregulated, and N/A [which applies only to the 'Total' entry])] and like seven or eight for space setting. Thoughts on this?

2021-03-25 15:13 UTC, kmagida110 commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
Yeah, sorry if that wasn't clear, we are literally going to load these to a database and hopefully will add things to them. 
1. Let's leave Month and Town separate because that is what it is now. 
2. I'll defer to you on this, you've been living with the data, if those are distinct categories then they are better to split up.

2021-03-25 15:18 UTC, bamader commented on data_sets/historical_care_4_kids/all_c4k_data.csv
> +town,sep 2017 infant/toddler regulated center,sep 2017 infant/toddler regulated group home,sep 2017 infant/toddler regulated family home,sep 2017 infant/toddler exempt exempt school,sep 2017 infant/t
No worries, it was definitely a "me" problem. Databases as creatures were unfamiliar to me before this so I'm still learning what plays well with them. But verbalizing things as "this is not a feature vector, this is a record with one number and a bunch of filters" is extremely helpful to me. I now understand what to do to fix this and so fix it I shall.

2021-03-25 20:35 UTC, bamader commented
Ignore the hundred thousand changes number--everything except like 250 of those is because of the CSV 😂

2021-03-26 01:34 UTC, kmagida110 approved these changes
Looks good! Two housekeeping items, can you move this to `src/data_integration/historical_care_4_kids/` and add a few lines of documentation to the README describing where the data is coming from and a quick summary of this for future us

2021-03-26 02:03 UTC, kmagida110 commented
Very fast data cleaning here actually, there are few towns that should be renamed:

Plymouth (Terryville) -> Plymouth
Pomfret Center -> Pomfret
Terryville -> Plymouth
Windham/Willimantic -> Windham

There are also some "Out of State" ones but we can ignore those

2021-03-26 12:11 UTC, merged