Add record deduplication
ctoec/data-visualization pull request #47
Opened 2021-04-16 18:02 UTC by bamader

## Background
This PR adds deduplication of child records to the data pulled from ECE Reporter. All children are assigned unique "visualization IDs" (for use with joins in superset) and all duplicate records are simply pointed to the visualization ID of the record they copy.

## Additional Context
No additional context needed.

2021-04-16 19:31 UTC, imcurtis approved these changes

2021-04-16 21:49 UTC, kmagida110 requested changes
A few small questions but overall this is great! Nice that this is relatively straight forward to implement, gotta love good docs.

2021-04-16 21:49 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    df = pd.read_csv(CHILD_FILE)
Can you add this file to gitignore just so the next person doesn't check it in by mistake. Also, can you add docs about where this comes from?

2021-04-16 21:49 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    comparator.exact('sasid', 'sasid', label='sasid')
For SASID is it worth relaxing exact to 95% or something like that since it is a user input and we should allow for some error there, whatever the equivalent of a transposed number is

2021-04-16 21:49 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    if show_ranks_distribution:
In an ideal world OEC makes the call here, maybe we have someone outside the data team but on Skylight make the call since they are a little further from the data

2021-04-16 21:49 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    matches = features[features.sum(axis=1) >= 5]
Can we have the 5 as a parameter so we can change it as needed? Relatedly _if_ we end up wanting to fuss with the parameter, the intake and ranking could be a different function that we can call with different parameters, not required here though.

2021-04-16 21:49 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +        dupes[df.iloc[idx[1]]['id']] = df.iloc[idx[0]]['id']
can you call df columns with names here? no big deal if that throws errors

2021-04-19 13:10 UTC, bamader commented on src/record_deduplication/dedupe.py
> +    df = pd.read_csv(CHILD_FILE)
"This" being the child file? I'm actually thinking I should probably delete this altogether and just parse a CSV given as a command line option, since we don't want any trace of the PII file anywhere in the repo.

2021-04-19 13:11 UTC, bamader commented on src/record_deduplication/dedupe.py
> +    comparator.exact('sasid', 'sasid', label='sasid')
Hmm yeah that's a good point. We should definitely keep the threshold high because that's one of the features that allows us to efficiently cut down on candidates, but you're probably right that a transposition should be allowable. I'll make the same adjustment to unique ID too since it's the same parsing logic that governs them both.

2021-04-19 13:17 UTC, bamader commented on src/record_deduplication/dedupe.py
> +    if show_ranks_distribution:
Sorry, is this comment addressed to what threshold should be used for determining the matching cutoff? In which case I def agree that OEC can do it, and changing the 5 to be a parameter (as below) will address that. Lemme know if there's something actionable here, otherwise I'll assume it's the same thing as below.

2021-04-19 13:19 UTC, bamader commented on src/record_deduplication/dedupe.py
> +        dupes[df.iloc[idx[1]]['id']] = df.iloc[idx[0]]['id']
As in, is it possible to directly build the dictionary with straight-up columns, rather than iterating? That is a good question, and I shall check.

2021-04-19 15:38 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    df = pd.read_csv(CHILD_FILE)
That works too, we'll probably refactor it to be a SQL query pulled into the function eventually anyways

2021-04-19 15:40 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    comparator.exact('sasid', 'sasid', label='sasid')
Sounds good! I'm less concerned about the unique ID since ECE creates that and hopefully it won't have major issues!

2021-04-19 15:41 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +    if show_ranks_distribution:
No actionable code here, more of a note that we should have somebody else assess the results and validate our assumptions.

2021-04-19 15:43 UTC, kmagida110 commented on src/record_deduplication/dedupe.py
> +        dupes[df.iloc[idx[1]]['id']] = df.iloc[idx[0]]['id']
I actually misunderstood what you were doing here but I think df.to_dict() with a reset index might get what you are talking about. Otherwise, it is fine as is.

2021-04-19 17:44 UTC, bamader commented on src/record_deduplication/dedupe.py
> +        dupes[df.iloc[idx[1]]['id']] = df.iloc[idx[0]]['id']
Tried this but it's having some issues with the multi-index. I agree it's fine as is, so I'm just gonna punt on the "perfect" way to do it (the better being the enemy of the good enough for our purposes).

2021-04-19 17:58 UTC, kmagida110 approved these changes
Let's do this!

2021-04-19 18:04 UTC, merged