Survey subsidy data
ctoec/data-visualization pull request #57
Opened 2021-05-24 18:23 UTC by imcurtis

## Background
This PR has some changes to the unmet_needs.py file which add subsidy data to the overall supply and demand for child care dataset.

## GitHub Issue
Replace this text with the GitHub issue link.
**NOTE: Please don't mark the issue as closed by this pull request!  Issues are to be closed manually within Zenhub upon merge & prod deploy.**

## Associated PRs
If applicable, replace this text with links to additional pull requests associated with this work.

## Validation Plan
The additions to the script are simple, and it produces a new CSV. This was checked to make sure that the subsidy columns were added.

## Additional Context
If there's anything additional information that those reviewing or validating this work should be aware of, please specify it here.

2021-05-24 19:25 UTC, kmagida110 requested changes
Thanks for doing this! There are a few changes here in the comments but it looks like it does what we need. Also, you probably don't need the notebook included here. It looks like you moved all the work there over to the script. Generally, if the notebook is for your own purposes to solve and problem and you have the results and code elsewhere you don't need to upload the notebook that you used as a scratchpad.

2021-05-24 19:25 UTC, kmagida110 commented on src/data_integration/unmet_needs/with_subsidy.csv
> +,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,children_needing_
We don't actually need this written to the repo. Once you get the function written you can run `get_supply_demand_with_cae` and write the resulting CSV to `src/final_data/'overall_supply_demand_with_cae.csv`.

2021-05-24 19:25 UTC, kmagida110 commented on src/final_data/get_subsidy.csv
> +,Unnamed: 0,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,childr
This file and the other get_subsidy one don't need to be added to the repo. Once you edit `get_supply_demand_with_cae` to save the full data with the subsidy to a file you can run that again and save it to `src/final_data/overall_supply_demand_with_cae.csv`

2021-05-24 19:25 UTC, kmagida110 commented on src/final_data/Survey respondents by income range.csv
> +Income_Range,Number_of_Respondents,Percent_of_Respondents
A few things with these files:
Can you make the column names lowercase?
Can you replace spaces with underscores in the filenames so they are easier to use in terminal and scripts?
Can you change the percentages to decimal so they are easier to read into a dataframe?

2021-05-24 19:36 UTC, imcurtis commented on src/data_integration/unmet_needs/.idea/.gitignore
> +# Default ignored files
Yes. I'll get this done once I've addressed your other comments below.

2021-05-24 19:45 UTC, imcurtis commented on src/data_integration/unmet_needs/get_subsidy.csv
> +,Unnamed: 0,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,childr
Should I go through with this if I end up removing the subsidy csv's?

2021-05-24 19:45 UTC, imcurtis commented on src/data_integration/unmet_needs/unmet_needs.py
>          df.to_csv(filename)
I ended up writing a csv to the final_data folder

2021-05-24 19:46 UTC, imcurtis commented on src/data_integration/unmet_needs/with_subsidy.csv
> +,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,children_needing_
I addressed this (hopefully). So the next commit you'll see the update

2021-05-24 19:47 UTC, imcurtis commented on src/final_data/get_subsidy.csv
> +,Unnamed: 0,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,childr
So is it worth it to delete those subsidy files before committing again?

2021-05-24 21:02 UTC, kmagida110 commented on src/final_data/get_subsidy.csv
> +,Unnamed: 0,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,childr
The ones in final_data should be deleted, yes

2021-05-24 21:03 UTC, kmagida110 commented on src/data_integration/unmet_needs/unmet_needs.py
> +    df.to_csv('/Users/amcurtis91/Documents/GitHub/data-visualization/src/final_data/overall_supply_demand_with_cae.csv')
Don't have this write to this location in the file, just have it write to the passed filename. The build_db.py script will call this function and specify where to write the file to

2021-05-24 21:03 UTC, kmagida110 commented on src/data_integration/unmet_needs/get_subsidy.csv
> +,Unnamed: 0,city,children_needing_care_demandestimated_infantstoddlers,available_spaces_for_children_supply_infantstoddlers,percent_of_need_met_infantstoddlers,shortage_of_care_infantstoddlers,childr
You'll still need the initial data so yes

2021-05-25 19:54 UTC, kmagida110 approved these changes
LGTM!

2021-05-25 21:23 UTC, bamader reviewed
Alex are you working with the most up to date versions of the various data files? I can't find any reason in here why the demand estimates for approximately half of the towns would change. None of the code here uploads any data changes (but also all the data files are in the `.gitignore` file) so it doesn't make sense. The only two things I can think of are that you're somehow running scripts on different demand estimation data, or the `merge` call in line 134 isn't actually behaving the way we want it to (maybe try `join` instead? Or check if the estimated demand values of the df are the same per city before and after merging?).

2021-05-26 13:58 UTC, imcurtis commented
> Alex are you working with the most up to date versions of the various data files? I can't find any reason in here why the demand estimates for approximately half of the towns would change. None of the code here uploads any data changes (but also all the data files are in the `.gitignore` file) so it doesn't make sense. The only two things I can think of are that you're somehow running scripts on different demand estimation data, or the `merge` call in line 134 isn't actually behaving the way we want it to (maybe try `join` instead? Or check if the estimated demand values of the df are the same per city before and after merging?).

Brandon, as far as I can tell I am working with up to date data files. I am merging the subsidy columns to the overall_supply_demand_by_town_with_cae.csv file, and outputting a overall_supply_demand_with_cae.csv file. I checked the estimated demand values of the files before and after merging and they are the same.

2021-05-27 17:15 UTC, jlhogan approved these changes

2021-05-27 17:15 UTC, jlhogan commented on .gitignore
> +.idea/
*/**/.idea?

2021-05-27 18:59 UTC, bamader commented on src/data_integration/unmet_needs/unmet_needs.py
>      df, rows_with_estimates = impute_corrected_demand_estimates(df, OVERALL_DEMAND_COLS, OVERALL_SUPPLY_COLS)
We shouldn't need this line anymore because none of our demand estimates are guesses. Alex, can you comment this out and push up whatever CSV gets generated as a result? I want to check the diff between that and the existing version just to make sure my hypothesis is right.

2021-05-27 19:00 UTC, imcurtis commented on src/data_integration/unmet_needs/unmet_needs.py
>      df, rows_with_estimates = impute_corrected_demand_estimates(df, OVERALL_DEMAND_COLS, OVERALL_SUPPLY_COLS)
Yep I can take care of that now

2021-05-28 12:06 UTC, bamader approved these changes

2021-05-28 15:04 UTC, merged